baseURL = "http://example.org/" # https://sjoerdev.github.io
theme = "LoveIt"
title = "Sjoerd Wouters"

languageCode = "en"
languageName = "English"

[params.author]
  name = "Sjoerd Wouters"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Blog"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "resume"
    pre = ""
    post = ""
    name = "Resume"
    url = "/resume/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    title = ""

[params]
  [params.header]
    [params.header.title]
      logo = ""
      name = "Sjoerd Wouters"
  [params.footer]
    enable = true
    hugo = true # Show hugo and theme info
    copyright = false
    author = false
    since = 2024
  [params.app]
    noFavicon = false
    svgFavicon = "/assets/favicon.svg"
  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.jpg"
      title = "Sjoerd Wouters"
      subtitle = ""
      typeit = false
      social = true
    [params.home.posts]
      enable = true
      paginate = 6
  [params.social]
    GitHub = "https://github.com/sjoerdev"
    Discord = "https://discordapp.com/users/906668622099927041"
    Email = "mailto:sjoerdwouters2004@gmail.com"
    Phone = "tel:+31628860939"
  [params.page]
    hiddenFromHomePage = false
    fontawesome = true
    linkToMarkdown = true
    [params.page.toc]
      enable = true
      keepStatic = false # if the toc should be to the side bar
      auto = true # auto collapse to sidebar
    [params.page.math]
      enable = true
    [params.page.code]
      copy = false # show the copy button
    [params.page.share]
      enable = false

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
    codeFences = true
    guessSyntax = false
    lineNumbersInTable = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true